channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - snakemake-minimal >=8.4.4
    - jinja2
    - fastqc
    - star
    - salmon
    - multiqc
    - r-base
    - r-rmarkdown
    - r-knitr
    - r-yaml
    - pandoc
    - r-tinytex        
    - r-htmltools
    - r-evaluate
    - r-stringr
    - r-jsonlite
    - r-digest
    - r-glue
    - r-flexdashboard
    - r-dt    
    - pip:
      #  at the time of writing - 7. Feb 24 - pysam on bioconda will require
      #  a lower python version than snakemake, install pysam
      #  using pip
      - pysam ==0.22