configfile: "config.yaml"

rule all:
    input:
        quantFile = expand("results/salmon/{sample}/quant.sf", sample=config["SAMPLES"]),
        htmlReport = config['HTMLREPORT']

rule fastqc:
    input:
        fa1 = lambda wildcards: f"{config['RAW_FILE_FOLDER']}/{wildcards.sample}_R1.fastq.gz",
        fa2 = lambda wildcards: f"{config['RAW_FILE_FOLDER']}/{wildcards.sample}_R2.fastq.gz"
    output:
        html1 = "results/fastqc/{sample}/{sample}_fastqc.html"
    params:
        fastqc_dir = "results/fastqc/{sample}/"    
    shell:
        "fastqc -o {params.fastqc_dir} {input.fa1} {input.fa2}"

rule runMultiqc:
    input:
        html1 = expand("results/fastqc/{sample}/{sample}_R1_fastqc.html", sample = config["SAMPLES"]),
        html2 = expand("results/fastqc/{sample}/{sample}_R2_fastqc.html", sample = config["SAMPLES"])
    output:
        multiqc_report = "results/multiqc/multiqc_report.html",
    params:
        fastqc_dir = "results/fastqc/",
        multiqc_dir = "results/multiqc/"
    shell:
        "multiqc {params.fastqc_dir} -o {params.multiqc_dir}"                     

rule salmon_quant_paired:
    input:
        multiqc_report = "results/multiqc/multiqc_report.html",
        fa1 = lambda wildcards: f"{config['RAW_FILE_FOLDER']}/{wildcards.sample}_R1.fastq.gz",
        fa2 = lambda wildcards: f"{config['RAW_FILE_FOLDER']}/{wildcards.sample}_R2.fastq.gz",
        salmon_index = config["SALMON_INDEX_FOLDER"]
    output:
        quantFile = "results/salmon/{sample}/quant.sf"
    params:
        quant_folder = "results/salmon/{sample}/"    
    shell:
        "salmon quant -i {input.salmon_index} -l A \
        -1 {input.fa1} -2 {input.fa2} \
        --validateMappings -o {params.quant_folder}"

rule deseq:
    input:
        quantFiles = expand("results/salmon/{sample}/quant.sf", sample=config["SAMPLES"]),
        rmarkdown = config["RMARKDOWN"],
        metadataFile = config["METADATAFILE"]
    output:
        htmlReport = config["HTMLREPORT"]
    shell:
        """
        Rscript -e "rmarkdown::render(
            '{input.rmarkdown}', 
            params = list(input_file='{input.metadataFile}'),
            output_file=basename('{output.htmlReport}'),
            output_dir=dirname('{output.htmlReport}')
        )"
        """